"""initial schema

Revision ID: 10207e245d08
Revises:
Create Date: 2026-09-06 22:55:02.507785
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import jst_api.db.types

revision: str = "10207e245d08"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PG_ONLY_NOTE = """PostgreSQL-only DDL.

pgvector and tsvector have no SQLite equivalent, so these statements are skipped
when the migration runs against SQLite. The evidence repository detects the
dialect and falls back to in-Python cosine similarity plus token matching, which
keeps tests and the offline demo on exactly the same schema chain.
"""


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    if _is_postgres():
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eval_cases",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("dataset", sa.String(length=60), nullable=False),
        sa.Column("case_key", sa.String(length=120), nullable=False),
        sa.Column("suite", sa.String(length=40), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("payload", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("expected", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("tags", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("dataset_version", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_cases")),
    )
    with op.batch_alter_table("eval_cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_cases_case_key"), ["case_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_cases_dataset"), ["dataset"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_cases_suite"), ["suite"], unique=False)

    op.create_table(
        "eval_runs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("suite", sa.String(length=40), nullable=False),
        sa.Column("dataset", sa.String(length=60), nullable=False),
        sa.Column("dataset_version", sa.String(length=20), nullable=False),
        sa.Column("variant", sa.String(length=60), nullable=False),
        sa.Column("git_sha", sa.String(length=40), nullable=True),
        sa.Column("prompt_versions", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("metrics", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("case_count", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    with op.batch_alter_table("eval_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_runs_suite"), ["suite"], unique=False)

    op.create_table(
        "regions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tagline", sa.String(length=240), nullable=False),
        sa.Column("prefectures", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("hub_place_slug", sa.String(length=80), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("gateways", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("min_recommended_nights", sa.Integer(), nullable=False),
        sa.Column("ideal_nights", sa.Integer(), nullable=False),
        sa.Column("max_useful_nights", sa.Integer(), nullable=False),
        sa.Column("public_transport_score", sa.Float(), nullable=False),
        sa.Column("car_free_possible", sa.Boolean(), nullable=False),
        sa.Column("car_recommended", sa.Boolean(), nullable=False),
        sa.Column("car_required_highlights", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("interest_strength", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("seasonal", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("booking_complexity", sa.Float(), nullable=False),
        sa.Column("luggage_friendliness", sa.Float(), nullable=False),
        sa.Column("step_free_score", sa.Float(), nullable=False),
        sa.Column("typical_daily_cost_jpy", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("overlaps_with_visited", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
    )
    with op.batch_alter_table("regions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_regions_code"), ["code"], unique=True)

    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("domain", sa.String(length=200), nullable=True),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("official_source", sa.Boolean(), nullable=False),
        sa.Column("trust_level", sa.String(length=20), nullable=False),
        sa.Column("region_code", sa.String(length=40), nullable=True),
        sa.Column("prefecture", sa.String(length=80), nullable=True),
        sa.Column("place_slug", sa.String(length=80), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.String(length=120), nullable=True),
        sa.Column("freshness_ttl_days", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_domain"), ["domain"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_place_slug"), ["place_slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_region_code"), ["region_code"], unique=False)
        batch_op.create_index(
            "ix_sources_region_type", ["region_code", "source_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sources_source_type"), ["source_type"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("plan", sa.String(length=30), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "booking_constraints",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("place_slug", sa.String(length=80), nullable=False),
        sa.Column("subject", sa.String(length=160), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("english_booking_available", sa.Boolean(), nullable=True),
        sa.Column("closed_months", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("closed_weekdays", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("requires_deposit", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(length=40), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_booking_constraints_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_constraints")),
    )
    with op.batch_alter_table("booking_constraints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_booking_constraints_place_slug"), ["place_slug"], unique=False
        )

    op.create_table(
        "eval_results",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("case_key", sa.String(length=120), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("metrics", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("detail", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("judge_model", sa.String(length=80), nullable=True),
        sa.Column("judge_prompt_version", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["eval_runs.id"],
            name=op.f("fk_eval_results_run_id_eval_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_results")),
    )
    with op.batch_alter_table("eval_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_results_case_key"), ["case_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_results_run_id"), ["run_id"], unique=False)

    op.create_table(
        "places",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("name_ja", sa.String(length=160), nullable=True),
        sa.Column("aliases", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("region_code", sa.String(length=40), nullable=True),
        sa.Column("prefecture", sa.String(length=80), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("place_kind", sa.String(length=40), nullable=False),
        sa.Column("is_gateway", sa.Boolean(), nullable=False),
        sa.Column("nearest_station", sa.String(length=160), nullable=True),
        sa.Column("typical_stay_nights", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("tags", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("car_recommended", sa.Boolean(), nullable=False),
        sa.Column("step_free", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["region_code"], ["regions.code"], name=op.f("fk_places_region_code_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
    )
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_places_name"), ["name"], unique=False)
        batch_op.create_index("ix_places_region_slug", ["region_code", "slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_places_slug"), ["slug"], unique=True)

    op.create_table(
        "source_documents",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column("cleaned_content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("doc_metadata", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_source_documents_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
    )
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_documents_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_source_documents_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "transport_constraints",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("from_slug", sa.String(length=80), nullable=False),
        sa.Column("to_slug", sa.String(length=80), nullable=False),
        sa.Column("mode", sa.String(length=40), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("transfers", sa.Integer(), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("requires_car", sa.Boolean(), nullable=False),
        sa.Column("last_departure_local", sa.String(length=5), nullable=True),
        sa.Column("final_leg_minutes", sa.Integer(), nullable=True),
        sa.Column("frequency_per_day", sa.Integer(), nullable=True),
        sa.Column("operator", sa.String(length=120), nullable=True),
        sa.Column("seasonal_note", sa.Text(), nullable=True),
        sa.Column("source_id", sa.String(length=40), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_transport_constraints_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transport_constraints")),
        sa.UniqueConstraint("from_slug", "to_slug", "mode", name="uq_transport_pair_mode"),
    )
    with op.batch_alter_table("transport_constraints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transport_constraints_from_slug"), ["from_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transport_constraints_to_slug"), ["to_slug"], unique=False
        )
        batch_op.create_index("ix_transport_from_to", ["from_slug", "to_slug"], unique=False)

    op.create_table(
        "trips",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("arrival_city", sa.String(length=80), nullable=True),
        sa.Column("departure_city", sa.String(length=80), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("total_nights", sa.Integer(), nullable=True),
        sa.Column("available_regional_nights", sa.Integer(), nullable=True),
        sa.Column("traveller_type", sa.String(length=20), nullable=True),
        sa.Column("party_size", sa.Integer(), nullable=True),
        sa.Column("driving", sa.String(length=20), nullable=True),
        sa.Column("pace", sa.String(length=20), nullable=True),
        sa.Column("budget", sa.String(length=20), nullable=True),
        sa.Column("large_luggage", sa.Boolean(), nullable=True),
        sa.Column("interests", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("mobility", jst_api.db.types.JSONBCompat(), nullable=True),
        sa.Column("preferences", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("candidate_region", sa.String(length=40), nullable=True),
        sa.Column("verified_warnings", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("decisions", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_trips_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    )
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trips_user_id"), ["user_id"], unique=False)

    op.create_table(
        "analyses",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("trip_id", sa.String(length=40), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.String(length=30), nullable=True),
        sa.Column("human_review_required", sa.Boolean(), nullable=False),
        sa.Column("input_payload", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("result_payload", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("evidence_ids", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("prompt_versions", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_analyses_trip_id_trips"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
    )
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analyses_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_analyses_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_analyses_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index("ix_analyses_trip_kind", ["trip_id", "kind"], unique=False)

    op.create_table(
        "candidate_regions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("trip_id", sa.String(length=40), nullable=False),
        sa.Column("region_code", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("deterministic_score", sa.Float(), nullable=True),
        sa.Column("fit_label", sa.String(length=30), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("score_breakdown", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_candidate_regions_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_regions")),
        sa.UniqueConstraint("trip_id", "region_code", name="uq_candidate_trip_region"),
    )
    with op.batch_alter_table("candidate_regions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_regions_region_code"), ["region_code"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_candidate_regions_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "evidence_chunks",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=40), nullable=False),
        sa.Column("document_id", sa.String(length=40), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("chunk_metadata", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("region_code", sa.String(length=40), nullable=True),
        sa.Column("place_slug", sa.String(length=80), nullable=True),
        sa.Column("topic", sa.String(length=40), nullable=False),
        sa.Column("transport_mode", sa.String(length=40), nullable=True),
        sa.Column("season_months", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("trust_level", sa.String(length=20), nullable=False),
        sa.Column("official_source", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("embedding_model", sa.String(length=80), nullable=False),
        sa.Column("embedding", jst_api.db.types.Vector(384), nullable=True),
        sa.Column("token_estimate", sa.Integer(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
            name=op.f("fk_evidence_chunks_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_evidence_chunks_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_chunks")),
    )
    with op.batch_alter_table("evidence_chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_chunks_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evidence_chunks_region_code"), ["region_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evidence_chunks_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_evidence_chunks_topic"), ["topic"], unique=False)
        batch_op.create_index("ix_evidence_place", ["place_slug"], unique=False)
        batch_op.create_index("ix_evidence_region_topic", ["region_code", "topic"], unique=False)

    op.create_table(
        "routes",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("trip_id", sa.String(length=40), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("arrival_city", sa.String(length=80), nullable=True),
        sa.Column("departure_city", sa.String(length=80), nullable=True),
        sa.Column("raw_input", sa.Text(), nullable=True),
        sa.Column("payload", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_routes_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routes")),
    )
    with op.batch_alter_table("routes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_routes_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "visited_places",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("trip_id", sa.String(length=40), nullable=False),
        sa.Column("raw_name", sa.String(length=160), nullable=False),
        sa.Column("place_slug", sa.String(length=80), nullable=True),
        sa.Column("region_code", sa.String(length=40), nullable=True),
        sa.Column("visited_year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_visited_places_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visited_places")),
        sa.UniqueConstraint("trip_id", "raw_name", name="uq_visited_trip_place"),
    )
    with op.batch_alter_table("visited_places", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_visited_places_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("analysis_id", sa.String(length=40), nullable=True),
        sa.Column("graph_name", sa.String(length=60), nullable=False),
        sa.Column("thread_id", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("node_path", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("step_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("model_calls", sa.Integer(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("fallbacks_used", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_agent_runs_analysis_id_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_runs_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_runs_graph_name"), ["graph_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_thread_id"), ["thread_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "feedback",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("analysis_id", sa.String(length=40), nullable=True),
        sa.Column("trip_id", sa.String(length=40), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("helpful", sa.Boolean(), nullable=True),
        sa.Column("category", sa.String(length=60), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("reported_inaccuracy", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_feedback_analysis_id_analyses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_feedback_trip_id_trips"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    op.create_table(
        "route_segments",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("route_id", sa.String(length=40), nullable=False),
        sa.Column("from_order", sa.Integer(), nullable=False),
        sa.Column("to_order", sa.Integer(), nullable=False),
        sa.Column("from_name", sa.String(length=160), nullable=False),
        sa.Column("to_name", sa.String(length=160), nullable=False),
        sa.Column("mode", sa.String(length=40), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("transfers", sa.Integer(), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("requires_car", sa.Boolean(), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("evidence_ids", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name=op.f("fk_route_segments_route_id_routes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_segments")),
    )
    with op.batch_alter_table("route_segments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_route_segments_route_id"), ["route_id"], unique=False)

    op.create_table(
        "verification_records",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("field_name", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(length=40), nullable=True),
        sa.Column("evidence_id", sa.String(length=40), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_by", sa.String(length=120), nullable=False),
        sa.Column("verification_method", sa.String(length=60), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_chunks.id"],
            name=op.f("fk_verification_records_evidence_id_evidence_chunks"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_verification_records_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_records")),
    )
    with op.batch_alter_table("verification_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_verification_records_subject"), ["subject"], unique=False
        )
        batch_op.create_index(
            "ix_verification_subject_field", ["subject", "field_name"], unique=False
        )

    op.create_table(
        "human_review_tasks",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("analysis_id", sa.String(length=40), nullable=True),
        sa.Column("run_id", sa.String(length=40), nullable=True),
        sa.Column("thread_id", sa.String(length=60), nullable=True),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("field_name", sa.String(length=120), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("candidate_values", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("evidence_ids", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("resolved_value", sa.Text(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.String(length=120), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resumed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_human_review_tasks_analysis_id_analyses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_human_review_tasks_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_review_tasks")),
    )
    with op.batch_alter_table("human_review_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_human_review_tasks_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_human_review_tasks_reason"), ["reason"], unique=False)
        batch_op.create_index(batch_op.f("ix_human_review_tasks_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_human_review_tasks_thread_id"), ["thread_id"], unique=False
        )
        batch_op.create_index("ix_review_status_reason", ["status", "reason"], unique=False)

    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=True),
        sa.Column("node", sa.String(length=60), nullable=True),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("transport", sa.String(length=20), nullable=False),
        sa.Column("arguments", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("result_summary", jst_api.db.types.JSONBCompat(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_tool_calls_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
    )
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.create_index("ix_tool_calls_name_ok", ["tool_name", "ok"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_calls_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_calls_tool_name"), ["tool_name"], unique=False)

    # ### end Alembic commands ###

    if _is_postgres():
        # Lexical half of hybrid retrieval: a GIN index over the same
        # ``search_text`` column the SQLite fallback tokenises.
        op.execute(
            "CREATE INDEX ix_evidence_chunks_fts "
            "ON evidence_chunks USING GIN (to_tsvector('english', search_text))"
        )
        op.execute(
            "CREATE INDEX ix_evidence_chunks_trgm "
            "ON evidence_chunks USING GIN (search_text gin_trgm_ops)"
        )
        # Dense half: HNSW gives sub-linear ANN with cosine distance. m/ef_construction
        # are pgvector defaults, adequate at the tens-of-thousands scale this
        # product operates at.
        op.execute(
            "CREATE INDEX ix_evidence_chunks_embedding_hnsw "
            "ON evidence_chunks USING hnsw (embedding vector_cosine_ops) "
            "WITH (m = 16, ef_construction = 64)"
        )
        op.execute("CREATE INDEX ix_places_name_trgm ON places USING GIN (name gin_trgm_ops)")


def downgrade() -> None:
    if _is_postgres():
        op.execute("DROP INDEX IF EXISTS ix_places_name_trgm")
        op.execute("DROP INDEX IF EXISTS ix_evidence_chunks_embedding_hnsw")
        op.execute("DROP INDEX IF EXISTS ix_evidence_chunks_trgm")
        op.execute("DROP INDEX IF EXISTS ix_evidence_chunks_fts")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_calls_tool_name"))
        batch_op.drop_index(batch_op.f("ix_tool_calls_run_id"))
        batch_op.drop_index("ix_tool_calls_name_ok")

    op.drop_table("tool_calls")
    with op.batch_alter_table("human_review_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_review_status_reason")
        batch_op.drop_index(batch_op.f("ix_human_review_tasks_thread_id"))
        batch_op.drop_index(batch_op.f("ix_human_review_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_human_review_tasks_reason"))
        batch_op.drop_index(batch_op.f("ix_human_review_tasks_analysis_id"))

    op.drop_table("human_review_tasks")
    with op.batch_alter_table("verification_records", schema=None) as batch_op:
        batch_op.drop_index("ix_verification_subject_field")
        batch_op.drop_index(batch_op.f("ix_verification_records_subject"))

    op.drop_table("verification_records")
    with op.batch_alter_table("route_segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_route_segments_route_id"))

    op.drop_table("route_segments")
    op.drop_table("feedback")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_trace_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_thread_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_graph_name"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_analysis_id"))

    op.drop_table("agent_runs")
    with op.batch_alter_table("visited_places", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_visited_places_trip_id"))

    op.drop_table("visited_places")
    with op.batch_alter_table("routes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_routes_trip_id"))

    op.drop_table("routes")
    with op.batch_alter_table("evidence_chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_evidence_region_topic")
        batch_op.drop_index("ix_evidence_place")
        batch_op.drop_index(batch_op.f("ix_evidence_chunks_topic"))
        batch_op.drop_index(batch_op.f("ix_evidence_chunks_source_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_chunks_region_code"))
        batch_op.drop_index(batch_op.f("ix_evidence_chunks_document_id"))

    op.drop_table("evidence_chunks")
    with op.batch_alter_table("candidate_regions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_regions_trip_id"))
        batch_op.drop_index(batch_op.f("ix_candidate_regions_region_code"))

    op.drop_table("candidate_regions")
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.drop_index("ix_analyses_trip_kind")
        batch_op.drop_index(batch_op.f("ix_analyses_trip_id"))
        batch_op.drop_index(batch_op.f("ix_analyses_status"))
        batch_op.drop_index(batch_op.f("ix_analyses_kind"))

    op.drop_table("analyses")
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trips_user_id"))

    op.drop_table("trips")
    with op.batch_alter_table("transport_constraints", schema=None) as batch_op:
        batch_op.drop_index("ix_transport_from_to")
        batch_op.drop_index(batch_op.f("ix_transport_constraints_to_slug"))
        batch_op.drop_index(batch_op.f("ix_transport_constraints_from_slug"))

    op.drop_table("transport_constraints")
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_documents_source_id"))
        batch_op.drop_index(batch_op.f("ix_source_documents_content_hash"))

    op.drop_table("source_documents")
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_places_slug"))
        batch_op.drop_index("ix_places_region_slug")
        batch_op.drop_index(batch_op.f("ix_places_name"))

    op.drop_table("places")
    with op.batch_alter_table("eval_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_results_run_id"))
        batch_op.drop_index(batch_op.f("ix_eval_results_case_key"))

    op.drop_table("eval_results")
    with op.batch_alter_table("booking_constraints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_booking_constraints_place_slug"))

    op.drop_table("booking_constraints")
    op.drop_table("users")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_source_type"))
        batch_op.drop_index("ix_sources_region_type")
        batch_op.drop_index(batch_op.f("ix_sources_region_code"))
        batch_op.drop_index(batch_op.f("ix_sources_place_slug"))
        batch_op.drop_index(batch_op.f("ix_sources_domain"))
        batch_op.drop_index(batch_op.f("ix_sources_content_hash"))

    op.drop_table("sources")
    with op.batch_alter_table("regions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_regions_code"))

    op.drop_table("regions")
    with op.batch_alter_table("eval_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_runs_suite"))

    op.drop_table("eval_runs")
    with op.batch_alter_table("eval_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_cases_suite"))
        batch_op.drop_index(batch_op.f("ix_eval_cases_dataset"))
        batch_op.drop_index(batch_op.f("ix_eval_cases_case_key"))

    op.drop_table("eval_cases")
    # ### end Alembic commands ###
