"""Seed booking constraints. DEMO DATA.

These are the *normalised* half of booking knowledge — lead times, language,
closure windows — used by deterministic checks. The narrative half ("ask your
previous hotel to phone for you") lives in the evidence corpus, because it does
not normalise into columns without losing its meaning.
"""

from __future__ import annotations

BOOKING_CONSTRAINTS: list[dict] = [
    {
        "place_slug": "nyuto-onsen",
        "subject": "Tsurunoyu ryokan",
        "lead_time_days": 90,
        "english_booking_available": False,
        "requires_deposit": True,
        "closed_months": [],
        "closed_weekdays": [],
        "note": "Telephone reservations in Japanese only, opening three months ahead. Cash only on arrival.",
    },
    {
        "place_slug": "ginzan-onsen",
        "subject": "Ginzan Onsen ryokan",
        "lead_time_days": 120,
        "english_booking_available": True,
        "requires_deposit": True,
        "closed_months": [],
        "closed_weekdays": [],
        "note": "Winter weekends book out months ahead. Confirm your arrival train so the inn can meet the bus.",
    },
    {
        "place_slug": "kurokawa-onsen",
        "subject": "Kurokawa ryokan village",
        "lead_time_days": 90,
        "english_booking_available": False,
        "requires_deposit": True,
        "closed_months": [],
        "closed_weekdays": [],
        "note": "Most inns are phone or Japanese-agency only. Dinner is at a fixed sitting; arrive before 18:00.",
    },
    {
        "place_slug": "naoshima",
        "subject": "Chichu Art Museum",
        "lead_time_days": 30,
        "english_booking_available": True,
        "requires_deposit": False,
        "closed_months": [],
        "closed_weekdays": [0],
        "note": "Timed online tickets only; no walk-up. Closed Mondays.",
    },
    {
        "place_slug": "teshima",
        "subject": "Teshima Art Museum",
        "lead_time_days": 14,
        "english_booking_available": True,
        "requires_deposit": False,
        "closed_months": [12, 1, 2],
        "closed_weekdays": [1],
        "note": "Closed Tuesdays and reduced winter opening.",
    },
    {
        "place_slug": "kamikochi",
        "subject": "Kamikochi valley lodges",
        "lead_time_days": 180,
        "english_booking_available": True,
        "requires_deposit": True,
        "closed_months": [12, 1, 2, 3],
        "closed_weekdays": [],
        "note": "Valley closed mid-November to mid-April. Autumn dates go a year ahead.",
    },
    {
        "place_slug": "shirakawa-go",
        "subject": "Nohi Bus Takayama–Shirakawa-go",
        "lead_time_days": 30,
        "english_booking_available": True,
        "requires_deposit": False,
        "closed_months": [],
        "closed_weekdays": [],
        "note": "Seat reservation required in autumn and for the winter light-up; English booking online.",
    },
    {
        "place_slug": "tateyama",
        "subject": "Alpine Route timed tickets",
        "lead_time_days": 30,
        "english_booking_available": True,
        "requires_deposit": False,
        "closed_months": [12, 1, 2, 3],
        "closed_weekdays": [],
        "note": "Closed December to mid-April. Morning slots in the opening weeks sell out.",
    },
    {
        "place_slug": "yufuin",
        "subject": "Yufuin no Mori limited express",
        "lead_time_days": 30,
        "english_booking_available": True,
        "requires_deposit": False,
        "closed_months": [],
        "closed_weekdays": [],
        "note": "Three services a day, all reserved; sells out weeks ahead in autumn.",
    },
    {
        "place_slug": "yakushima",
        "subject": "Jomon Sugi trailhead bus",
        "lead_time_days": 7,
        "english_booking_available": False,
        "requires_deposit": False,
        "closed_months": [],
        "closed_weekdays": [],
        "note": "Early-morning access bus must be booked; private cars are barred from the road in season.",
    },
    {
        "place_slug": "eiheiji",
        "subject": "Eiheiji overnight stay",
        "lead_time_days": 60,
        "english_booking_available": False,
        "requires_deposit": True,
        "closed_months": [],
        "closed_weekdays": [],
        "note": "Temple lodging is a religious practice, not a hotel; arranged by phone well in advance.",
    },
]
