"""Seed place catalogue. DEMO DATA — see ``seed/regions.py`` for the caveat.

Coordinates are real (they drive the geometric fallback and the backtracking
rule); descriptions and stay lengths are hand-authored approximations.
"""

from __future__ import annotations

# slug, name, name_ja, aliases, region, prefecture, lat, lon, kind, gateway,
# nearest_station, typical_nights, car_recommended, step_free, tags, summary
PLACES: list[dict] = [
    # ---- gateways ----------------------------------------------------------
    {
        "slug": "tokyo",
        "name": "Tokyo",
        "name_ja": "東京",
        "aliases": ["haneda", "narita", "tokyo station"],
        "region_code": None,
        "prefecture": "Tokyo",
        "lat": 35.6812,
        "lon": 139.7671,
        "place_kind": "gateway",
        "is_gateway": True,
        "nearest_station": "Tokyo Station",
        "typical_stay_nights": 3,
        "car_recommended": False,
        "step_free": True,
        "tags": ["city", "food", "nightlife", "art"],
        "summary": "Primary international gateway and the start point for the Tohoku, Hokuriku and Nagano shinkansen lines.",
    },
    {
        "slug": "osaka",
        "name": "Osaka",
        "name_ja": "大阪",
        "aliases": ["kansai", "kix", "itami"],
        "region_code": None,
        "prefecture": "Osaka",
        "lat": 34.7025,
        "lon": 135.4959,
        "place_kind": "gateway",
        "is_gateway": True,
        "nearest_station": "Shin-Osaka",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["city", "food", "nightlife"],
        "summary": "Kansai gateway; the natural start point for Shikoku and western Japan.",
    },
    {
        "slug": "kyoto",
        "name": "Kyoto",
        "name_ja": "京都",
        "aliases": [],
        "region_code": None,
        "prefecture": "Kyoto",
        "lat": 35.0116,
        "lon": 135.7681,
        "place_kind": "gateway",
        "is_gateway": True,
        "nearest_station": "Kyoto Station",
        "typical_stay_nights": 3,
        "car_recommended": False,
        "step_free": True,
        "tags": ["culture", "city"],
        "summary": "Golden-route anchor; included here as a travel-history reference point, not a regional destination.",
    },
    {
        "slug": "nagoya",
        "name": "Nagoya",
        "name_ja": "名古屋",
        "aliases": ["chubu", "centrair"],
        "region_code": None,
        "prefecture": "Aichi",
        "lat": 35.1709,
        "lon": 136.8815,
        "place_kind": "gateway",
        "is_gateway": True,
        "nearest_station": "Nagoya Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["city", "food"],
        "summary": "Central gateway; the shortest approach to the Kiso valley and Takayama.",
    },
    {
        "slug": "sapporo",
        "name": "Sapporo",
        "name_ja": "札幌",
        "aliases": ["new chitose", "cts"],
        "region_code": None,
        "prefecture": "Hokkaido",
        "lat": 43.0621,
        "lon": 141.3544,
        "place_kind": "gateway",
        "is_gateway": True,
        "nearest_station": "Sapporo Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["city", "food", "snow"],
        "summary": "Hokkaido gateway.",
    },
    # ---- Tohoku ------------------------------------------------------------
    {
        "slug": "sendai",
        "name": "Sendai",
        "name_ja": "仙台",
        "aliases": [],
        "region_code": "tohoku",
        "prefecture": "Miyagi",
        "lat": 38.2682,
        "lon": 140.8694,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Sendai Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["city", "food", "culture"],
        "summary": "Tohoku's largest city and the region's transport hub. 1h30 from Tokyo on the Tohoku Shinkansen with no transfer.",
    },
    {
        "slug": "matsushima",
        "name": "Matsushima",
        "name_ja": "松島",
        "aliases": ["matsushima bay"],
        "region_code": "tohoku",
        "prefecture": "Miyagi",
        "lat": 38.3742,
        "lon": 141.0603,
        "place_kind": "town",
        "is_gateway": False,
        "nearest_station": "Matsushima-Kaigan",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["coast", "culture", "nature"],
        "summary": "Pine-island bay 40 minutes from Sendai on the local line — a classic half-day trip rather than an overnight.",
    },
    {
        "slug": "yamadera",
        "name": "Yamadera",
        "name_ja": "山寺",
        "aliases": ["risshaku-ji", "yama-dera"],
        "region_code": "tohoku",
        "prefecture": "Yamagata",
        "lat": 38.3128,
        "lon": 140.4436,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Yamadera Station",
        "typical_stay_nights": 0,
        "car_recommended": False,
        "step_free": False,
        "tags": ["culture", "hiking", "nature"],
        "summary": "Cliff temple reached by 1,015 stone steps, on the local line between Sendai and Yamagata. A stop, not a stay.",
    },
    {
        "slug": "ginzan-onsen",
        "name": "Ginzan Onsen",
        "name_ja": "銀山温泉",
        "aliases": ["ginzan", "ginzan hot spring"],
        "region_code": "tohoku",
        "prefecture": "Yamagata",
        "lat": 38.5722,
        "lon": 140.5308,
        "place_kind": "onsen",
        "is_gateway": False,
        "nearest_station": "Oishida Station (bus)",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["onsen", "snow", "culture"],
        "summary": "Taisho-era gaslit onsen street in a narrow valley. Reached only by bus from Oishida; the village is closed to daytime cars in winter.",
    },
    {
        "slug": "zao-onsen",
        "name": "Zao Onsen",
        "name_ja": "蔵王温泉",
        "aliases": ["zao"],
        "region_code": "tohoku",
        "prefecture": "Yamagata",
        "lat": 38.1667,
        "lon": 140.4000,
        "place_kind": "onsen",
        "is_gateway": False,
        "nearest_station": "Yamagata Station (bus)",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["onsen", "snow", "hiking"],
        "summary": "Sulphur onsen and ski village; famous for the winter 'snow monsters' on the ropeway.",
    },
    {
        "slug": "yamagata",
        "name": "Yamagata",
        "name_ja": "山形",
        "aliases": [],
        "region_code": "tohoku",
        "prefecture": "Yamagata",
        "lat": 38.2554,
        "lon": 140.3396,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Yamagata Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "city"],
        "summary": "Transfer point for Zao, Ginzan and the Dewa Sanzan; workmanlike rather than scenic.",
    },
    {
        "slug": "morioka",
        "name": "Morioka",
        "name_ja": "盛岡",
        "aliases": [],
        "region_code": "tohoku",
        "prefecture": "Iwate",
        "lat": 39.7036,
        "lon": 141.1527,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Morioka Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "city"],
        "summary": "Noodle city and the gateway to Nyuto Onsen and Kakunodate.",
    },
    {
        "slug": "kakunodate",
        "name": "Kakunodate",
        "name_ja": "角館",
        "aliases": ["samurai district"],
        "region_code": "tohoku",
        "prefecture": "Akita",
        "lat": 39.5964,
        "lon": 140.5622,
        "place_kind": "town",
        "is_gateway": False,
        "nearest_station": "Kakunodate Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["culture", "nature"],
        "summary": "Preserved samurai quarter on the Akita Shinkansen line — genuinely walkable from the station.",
    },
    {
        "slug": "nyuto-onsen",
        "name": "Nyuto Onsen",
        "name_ja": "乳頭温泉郷",
        "aliases": ["nyuto", "tsurunoyu"],
        "region_code": "tohoku",
        "prefecture": "Akita",
        "lat": 39.7972,
        "lon": 140.7833,
        "place_kind": "onsen",
        "is_gateway": False,
        "nearest_station": "Tazawako Station (bus)",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["onsen", "nature", "snow"],
        "summary": "Cluster of remote mountain baths above Lake Tazawa. Tsurunoyu, the best known, takes bookings by phone only.",
    },
    {
        "slug": "aomori",
        "name": "Aomori",
        "name_ja": "青森",
        "aliases": [],
        "region_code": "tohoku",
        "prefecture": "Aomori",
        "lat": 40.8246,
        "lon": 140.7406,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Shin-Aomori Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "coast", "art", "snow"],
        "summary": "Northern terminus of Honshu. Nebuta museum, superb seafood market, and the jumping-off point for Hakodate.",
    },
    {
        "slug": "hirosaki",
        "name": "Hirosaki",
        "name_ja": "弘前",
        "aliases": [],
        "region_code": "tohoku",
        "prefecture": "Aomori",
        "lat": 40.6031,
        "lon": 140.4638,
        "place_kind": "town",
        "is_gateway": False,
        "nearest_station": "Hirosaki Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["culture", "nature"],
        "summary": "Castle town with the best cherry blossom in Tohoku and a walkable old quarter.",
    },
    {
        "slug": "oirase",
        "name": "Oirase Gorge",
        "name_ja": "奥入瀬渓流",
        "aliases": ["oirase stream", "towada"],
        "region_code": "tohoku",
        "prefecture": "Aomori",
        "lat": 40.5386,
        "lon": 140.9583,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Aomori Station (bus)",
        "typical_stay_nights": 1,
        "car_recommended": True,
        "step_free": False,
        "tags": ["nature", "hiking"],
        "summary": "Stream-side walking trail to Lake Towada. Buses run only in the green season and are sparse.",
    },
    {
        "slug": "hakodate",
        "name": "Hakodate",
        "name_ja": "函館",
        "aliases": [],
        "region_code": None,
        "prefecture": "Hokkaido",
        "lat": 41.7688,
        "lon": 140.7288,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Shin-Hakodate-Hokuto",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "coast", "city", "snow"],
        "summary": "Southern Hokkaido port city. Reachable from Aomori by Hokkaido Shinkansen, but it is a different region with its own travel logic.",
    },
    # ---- Nagano / Alps -----------------------------------------------------
    {
        "slug": "nagano",
        "name": "Nagano",
        "name_ja": "長野",
        "aliases": [],
        "region_code": "nagano_alps",
        "prefecture": "Nagano",
        "lat": 36.6486,
        "lon": 138.1948,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Nagano Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["culture", "city", "snow"],
        "summary": "Zenko-ji temple town and the transfer point for the snow monkeys and Nozawa Onsen. 1h20 from Tokyo.",
    },
    {
        "slug": "matsumoto",
        "name": "Matsumoto",
        "name_ja": "松本",
        "aliases": [],
        "region_code": "nagano_alps",
        "prefecture": "Nagano",
        "lat": 36.2381,
        "lon": 137.9720,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Matsumoto Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["culture", "city", "art"],
        "summary": "Original black castle keep, a good food scene, and the base for Kamikochi.",
    },
    {
        "slug": "kamikochi",
        "name": "Kamikochi",
        "name_ja": "上高地",
        "aliases": [],
        "region_code": "nagano_alps",
        "prefecture": "Nagano",
        "lat": 36.2489,
        "lon": 137.6383,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Shin-Shimashima (bus)",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["nature", "hiking"],
        "summary": "Alpine valley closed to private cars year-round; access is by bus or taxi only, and the whole valley shuts mid-November to mid-April.",
    },
    {
        "slug": "hakuba",
        "name": "Hakuba",
        "name_ja": "白馬",
        "aliases": ["hakuba valley"],
        "region_code": "nagano_alps",
        "prefecture": "Nagano",
        "lat": 36.6983,
        "lon": 137.8619,
        "place_kind": "town",
        "is_gateway": False,
        "nearest_station": "Hakuba Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["snow", "hiking", "nature"],
        "summary": "Olympic ski valley; in summer a serious alpine hiking base.",
    },
    {
        "slug": "nozawa-onsen",
        "name": "Nozawa Onsen",
        "name_ja": "野沢温泉",
        "aliases": ["nozawa"],
        "region_code": "nagano_alps",
        "prefecture": "Nagano",
        "lat": 36.9214,
        "lon": 138.4436,
        "place_kind": "onsen",
        "is_gateway": False,
        "nearest_station": "Iiyama Station (bus)",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": False,
        "tags": ["onsen", "snow", "culture"],
        "summary": "Ski village where thirteen free public bathhouses still run on the old community rota.",
    },
    {
        "slug": "jigokudani",
        "name": "Jigokudani Monkey Park",
        "name_ja": "地獄谷野猿公苑",
        "aliases": ["snow monkeys", "yudanaka"],
        "region_code": "nagano_alps",
        "prefecture": "Nagano",
        "lat": 36.7333,
        "lon": 138.4622,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Yudanaka Station (bus)",
        "typical_stay_nights": 0,
        "car_recommended": False,
        "step_free": False,
        "tags": ["nature"],
        "summary": "Bathing macaques, reached by a 1.6 km forest walk from the bus stop. Half a day from Nagano.",
    },
    {
        "slug": "narai",
        "name": "Narai-juku",
        "name_ja": "奈良井宿",
        "aliases": ["narai", "kiso valley"],
        "region_code": "nagano_alps",
        "prefecture": "Nagano",
        "lat": 35.9333,
        "lon": 137.8167,
        "place_kind": "town",
        "is_gateway": False,
        "nearest_station": "Narai Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["culture", "hiking"],
        "summary": "Best-preserved post town on the Nakasendo, on a local line with roughly hourly service.",
    },
    {
        "slug": "takayama",
        "name": "Takayama",
        "name_ja": "高山",
        "aliases": ["hida-takayama"],
        "region_code": "nagano_alps",
        "prefecture": "Gifu",
        "lat": 36.1461,
        "lon": 137.2522,
        "place_kind": "town",
        "is_gateway": True,
        "nearest_station": "Takayama Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["culture", "food", "onsen"],
        "summary": "Old merchant town in the Hida mountains; the usual base for Shirakawa-go.",
    },
    {
        "slug": "shirakawa-go",
        "name": "Shirakawa-go",
        "name_ja": "白川郷",
        "aliases": ["shirakawago"],
        "region_code": "nagano_alps",
        "prefecture": "Gifu",
        "lat": 36.2578,
        "lon": 136.9061,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Shirakawa-go bus terminal",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["culture", "snow", "nature"],
        "summary": "Thatched farmhouse village on the Takayama–Kanazawa highway bus. Reservations required on that bus in peak season.",
    },
    # ---- Hokuriku ----------------------------------------------------------
    {
        "slug": "kanazawa",
        "name": "Kanazawa",
        "name_ja": "金沢",
        "aliases": [],
        "region_code": "hokuriku",
        "prefecture": "Ishikawa",
        "lat": 36.5613,
        "lon": 136.6562,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Kanazawa Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "culture", "art", "city"],
        "summary": "Kenrokuen, the 21st Century Museum, Omicho market and a gold-leaf craft tradition. Direct shinkansen from Tokyo.",
    },
    {
        "slug": "toyama",
        "name": "Toyama",
        "name_ja": "富山",
        "aliases": [],
        "region_code": "hokuriku",
        "prefecture": "Toyama",
        "lat": 36.6959,
        "lon": 137.2137,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Toyama Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "coast"],
        "summary": "Bay seafood and the eastern entrance to the Tateyama Alpine Route.",
    },
    {
        "slug": "wajima",
        "name": "Wajima",
        "name_ja": "輪島",
        "aliases": ["noto", "noto peninsula"],
        "region_code": "hokuriku",
        "prefecture": "Ishikawa",
        "lat": 37.3906,
        "lon": 136.8992,
        "place_kind": "town",
        "is_gateway": False,
        "nearest_station": "Kanazawa (bus, 2h)",
        "typical_stay_nights": 1,
        "car_recommended": True,
        "step_free": False,
        "tags": ["coast", "culture", "food"],
        "summary": "Lacquerware town on the outer Noto coast. Rail service ended in 2001; access is by express bus or car.",
    },
    {
        "slug": "fukui",
        "name": "Fukui",
        "name_ja": "福井",
        "aliases": [],
        "region_code": "hokuriku",
        "prefecture": "Fukui",
        "lat": 36.0641,
        "lon": 136.2196,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Fukui Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["culture", "food"],
        "summary": "Base for Eiheiji temple and the dinosaur museum; on the extended Hokuriku Shinkansen.",
    },
    {
        "slug": "eiheiji",
        "name": "Eiheiji",
        "name_ja": "永平寺",
        "aliases": ["eihei-ji"],
        "region_code": "hokuriku",
        "prefecture": "Fukui",
        "lat": 36.0553,
        "lon": 136.3556,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Fukui Station (bus)",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["culture"],
        "summary": "Working Soto Zen training monastery. Overnight stays exist but must be arranged well in advance.",
    },
    {
        "slug": "tateyama",
        "name": "Tateyama Alpine Route",
        "name_ja": "立山黒部アルペンルート",
        "aliases": ["alpine route", "kurobe"],
        "region_code": "hokuriku",
        "prefecture": "Toyama",
        "lat": 36.5772,
        "lon": 137.6089,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Dentetsu-Toyama",
        "typical_stay_nights": 0,
        "car_recommended": False,
        "step_free": False,
        "tags": ["nature", "snow", "hiking"],
        "summary": "Cable-car, bus and ropeway traverse of the Northern Alps. Open roughly mid-April to end November only.",
    },
    # ---- Shikoku / Setouchi -------------------------------------------------
    {
        "slug": "takamatsu",
        "name": "Takamatsu",
        "name_ja": "高松",
        "aliases": [],
        "region_code": "shikoku_setouchi",
        "prefecture": "Kagawa",
        "lat": 34.3428,
        "lon": 134.0466,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Takamatsu Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "coast", "art"],
        "summary": "Udon capital, Ritsurin garden, and the ferry port for the Setouchi art islands.",
    },
    {
        "slug": "naoshima",
        "name": "Naoshima",
        "name_ja": "直島",
        "aliases": ["benesse", "chichu"],
        "region_code": "shikoku_setouchi",
        "prefecture": "Kagawa",
        "lat": 34.4614,
        "lon": 133.9950,
        "place_kind": "island",
        "is_gateway": False,
        "nearest_station": "Miyanoura Port",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["art", "coast"],
        "summary": "Art island. Chichu Art Museum requires timed tickets bought online in advance; the last ferry back is early.",
    },
    {
        "slug": "teshima",
        "name": "Teshima",
        "name_ja": "豊島",
        "aliases": [],
        "region_code": "shikoku_setouchi",
        "prefecture": "Kagawa",
        "lat": 34.4894,
        "lon": 134.1017,
        "place_kind": "island",
        "is_gateway": False,
        "nearest_station": "Ieura Port",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["art", "coast", "nature"],
        "summary": "Quieter art island next to Naoshima. Few ferries; a day trip has to be planned around the timetable, not the art.",
    },
    {
        "slug": "matsuyama",
        "name": "Matsuyama",
        "name_ja": "松山",
        "aliases": ["dogo onsen", "dogo"],
        "region_code": "shikoku_setouchi",
        "prefecture": "Ehime",
        "lat": 33.8416,
        "lon": 132.7657,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Matsuyama Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["onsen", "culture", "city"],
        "summary": "Dogo Onsen, said to be Japan's oldest bathhouse, plus a hilltop castle reached by ropeway.",
    },
    {
        "slug": "iya-valley",
        "name": "Iya Valley",
        "name_ja": "祖谷渓",
        "aliases": ["iya", "oboke", "kazurabashi"],
        "region_code": "shikoku_setouchi",
        "prefecture": "Tokushima",
        "lat": 33.8833,
        "lon": 133.8000,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Oboke Station (bus)",
        "typical_stay_nights": 1,
        "car_recommended": True,
        "step_free": False,
        "tags": ["nature", "hiking", "onsen"],
        "summary": "Steep gorge valley with vine bridges and thatched farmhouses. Buses beyond Oboke run a handful of times a day.",
    },
    {
        "slug": "kochi",
        "name": "Kochi",
        "name_ja": "高知",
        "aliases": [],
        "region_code": "shikoku_setouchi",
        "prefecture": "Kochi",
        "lat": 33.5597,
        "lon": 133.5311,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Kochi Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "coast", "nightlife"],
        "summary": "Pacific-side city with the best night market in Shikoku and seared bonito done properly.",
    },
    {
        "slug": "onomichi",
        "name": "Onomichi",
        "name_ja": "尾道",
        "aliases": ["shimanami kaido", "shimanami"],
        "region_code": "shikoku_setouchi",
        "prefecture": "Hiroshima",
        "lat": 34.4090,
        "lon": 133.2050,
        "place_kind": "town",
        "is_gateway": True,
        "nearest_station": "Onomichi Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": False,
        "tags": ["coast", "hiking", "food"],
        "summary": "Northern end of the Shimanami Kaido cycling route across the Inland Sea.",
    },
    # ---- Kyushu ------------------------------------------------------------
    {
        "slug": "fukuoka",
        "name": "Fukuoka",
        "name_ja": "福岡",
        "aliases": ["hakata", "fuk"],
        "region_code": "kyushu",
        "prefecture": "Fukuoka",
        "lat": 33.5904,
        "lon": 130.4017,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Hakata Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "city", "nightlife"],
        "summary": "Kyushu's gateway. The airport is two subway stops from Hakata — five minutes, not an hour.",
    },
    {
        "slug": "beppu",
        "name": "Beppu",
        "name_ja": "別府",
        "aliases": [],
        "region_code": "kyushu",
        "prefecture": "Oita",
        "lat": 33.2794,
        "lon": 131.5006,
        "place_kind": "onsen",
        "is_gateway": True,
        "nearest_station": "Beppu Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["onsen", "coast"],
        "summary": "The highest hot-spring output in Japan. Big, slightly faded, and genuinely easy to reach by train.",
    },
    {
        "slug": "yufuin",
        "name": "Yufuin",
        "name_ja": "湯布院",
        "aliases": ["yufu"],
        "region_code": "kyushu",
        "prefecture": "Oita",
        "lat": 33.2647,
        "lon": 131.3572,
        "place_kind": "onsen",
        "is_gateway": False,
        "nearest_station": "Yufuin Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["onsen", "nature", "art"],
        "summary": "Polished onsen village under Mount Yufu; reachable by the Yufuin no Mori limited express from Hakata.",
    },
    {
        "slug": "kurokawa-onsen",
        "name": "Kurokawa Onsen",
        "name_ja": "黒川温泉",
        "aliases": ["kurokawa"],
        "region_code": "kyushu",
        "prefecture": "Kumamoto",
        "lat": 33.0872,
        "lon": 131.1078,
        "place_kind": "onsen",
        "is_gateway": False,
        "nearest_station": "Aso Station (bus)",
        "typical_stay_nights": 1,
        "car_recommended": True,
        "step_free": False,
        "tags": ["onsen", "nature"],
        "summary": "Riverside ryokan village with a shared bath pass. No railway; a small number of highway buses serve it daily.",
    },
    {
        "slug": "kumamoto",
        "name": "Kumamoto",
        "name_ja": "熊本",
        "aliases": [],
        "region_code": "kyushu",
        "prefecture": "Kumamoto",
        "lat": 32.8031,
        "lon": 130.7079,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Kumamoto Station",
        "typical_stay_nights": 1,
        "car_recommended": False,
        "step_free": True,
        "tags": ["culture", "food", "city"],
        "summary": "Castle city on the Kyushu Shinkansen; the western gateway to Aso.",
    },
    {
        "slug": "aso",
        "name": "Mount Aso",
        "name_ja": "阿蘇",
        "aliases": ["aso caldera", "aso-san"],
        "region_code": "kyushu",
        "prefecture": "Kumamoto",
        "lat": 32.8845,
        "lon": 131.1040,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Aso Station",
        "typical_stay_nights": 1,
        "car_recommended": True,
        "step_free": False,
        "tags": ["nature", "hiking", "onsen"],
        "summary": "One of the world's largest calderas, with an active crater whose access closes without warning on gas readings.",
    },
    {
        "slug": "kagoshima",
        "name": "Kagoshima",
        "name_ja": "鹿児島",
        "aliases": ["sakurajima"],
        "region_code": "kyushu",
        "prefecture": "Kagoshima",
        "lat": 31.5966,
        "lon": 130.5571,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Kagoshima-Chuo",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["food", "coast", "nature", "city"],
        "summary": "Southern terminus of the Kyushu Shinkansen, facing the active Sakurajima volcano across the bay.",
    },
    {
        "slug": "nagasaki",
        "name": "Nagasaki",
        "name_ja": "長崎",
        "aliases": [],
        "region_code": "kyushu",
        "prefecture": "Nagasaki",
        "lat": 32.7503,
        "lon": 129.8779,
        "place_kind": "city",
        "is_gateway": True,
        "nearest_station": "Nagasaki Station",
        "typical_stay_nights": 2,
        "car_recommended": False,
        "step_free": True,
        "tags": ["culture", "coast", "food", "city"],
        "summary": "Port city with a distinct Dutch-Chinese history; now on the Nishi-Kyushu Shinkansen via a transfer at Takeo-Onsen.",
    },
    {
        "slug": "takachiho",
        "name": "Takachiho",
        "name_ja": "高千穂",
        "aliases": ["takachiho gorge"],
        "region_code": "kyushu",
        "prefecture": "Miyazaki",
        "lat": 32.7117,
        "lon": 131.3078,
        "place_kind": "sight",
        "is_gateway": False,
        "nearest_station": "Nobeoka (bus, 1h30)",
        "typical_stay_nights": 1,
        "car_recommended": True,
        "step_free": False,
        "tags": ["nature", "culture"],
        "summary": "Mythological gorge in inland Miyazaki. The local railway closed in 2008; access is bus or car only.",
    },
    {
        "slug": "yakushima",
        "name": "Yakushima",
        "name_ja": "屋久島",
        "aliases": [],
        "region_code": "kyushu",
        "prefecture": "Kagoshima",
        "lat": 30.3583,
        "lon": 130.5417,
        "place_kind": "island",
        "is_gateway": False,
        "nearest_station": "Miyanoura Port (ferry/air from Kagoshima)",
        "typical_stay_nights": 2,
        "car_recommended": True,
        "step_free": False,
        "tags": ["nature", "hiking", "coast"],
        "summary": "Ancient cedar forest island. Rain is close to constant; ferries cancel in rough weather.",
    },
]
