"""Seed transport records. DEMO DATA.

Durations are hand-authored door-to-door approximations including typical access
and transfer waits. They are marked ``is_demo=True`` and every result built on
them carries the demo badge. They are good enough to demonstrate the rules
engine honestly; they are not a timetable and the product says so.

``last_departure_local`` + ``final_leg_minutes`` are what let rule
``R06_last_connection`` reason about missing the last bus of the day.
"""

from __future__ import annotations

# from, to, mode, minutes, transfers, km, requires_car, last_dep, final_leg, freq/day, operator, note
TRANSPORT: list[dict] = [
    # ---- gateway → region hubs --------------------------------------------
    {
        "from_slug": "tokyo",
        "to_slug": "sendai",
        "mode": "shinkansen",
        "duration_minutes": 95,
        "transfers": 0,
        "distance_km": 352,
        "frequency_per_day": 60,
        "operator": "JR East (Tohoku Shinkansen)",
        "seasonal_note": "Hayabusa services are all-reserved; buy ahead in peak weeks.",
    },
    {
        "from_slug": "tokyo",
        "to_slug": "aomori",
        "mode": "shinkansen",
        "duration_minutes": 200,
        "transfers": 1,
        "distance_km": 675,
        "frequency_per_day": 15,
        "operator": "JR East",
        "seasonal_note": "Shin-Aomori is a further 6 min local train from Aomori city centre.",
    },
    {
        "from_slug": "tokyo",
        "to_slug": "nagano",
        "mode": "shinkansen",
        "duration_minutes": 85,
        "transfers": 0,
        "distance_km": 222,
        "frequency_per_day": 40,
        "operator": "JR East (Hokuriku Shinkansen)",
    },
    {
        "from_slug": "tokyo",
        "to_slug": "matsumoto",
        "mode": "limited_express",
        "duration_minutes": 160,
        "transfers": 0,
        "distance_km": 235,
        "frequency_per_day": 12,
        "operator": "JR East (Azusa)",
    },
    {
        "from_slug": "tokyo",
        "to_slug": "kanazawa",
        "mode": "shinkansen",
        "duration_minutes": 155,
        "transfers": 0,
        "distance_km": 450,
        "frequency_per_day": 25,
        "operator": "JR West (Kagayaki/Hakutaka)",
    },
    {
        "from_slug": "tokyo",
        "to_slug": "takamatsu",
        "mode": "shinkansen",
        "duration_minutes": 265,
        "transfers": 1,
        "distance_km": 690,
        "frequency_per_day": 20,
        "operator": "JR (via Okayama, Marine Liner)",
    },
    {
        "from_slug": "tokyo",
        "to_slug": "fukuoka",
        "mode": "flight",
        "duration_minutes": 195,
        "transfers": 1,
        "distance_km": 880,
        "frequency_per_day": 50,
        "operator": "ANA/JAL",
        "seasonal_note": "Door-to-door including Haneda access and the 5-minute Fukuoka airport subway.",
    },
    {
        "from_slug": "tokyo",
        "to_slug": "fukuoka",
        "mode": "shinkansen",
        "duration_minutes": 310,
        "transfers": 0,
        "distance_km": 1069,
        "frequency_per_day": 30,
        "operator": "JR Central/West (Nozomi)",
    },
    {
        "from_slug": "osaka",
        "to_slug": "takamatsu",
        "mode": "limited_express",
        "duration_minutes": 120,
        "transfers": 1,
        "distance_km": 190,
        "frequency_per_day": 30,
        "operator": "JR (via Okayama)",
    },
    {
        "from_slug": "osaka",
        "to_slug": "kanazawa",
        "mode": "limited_express",
        "duration_minutes": 155,
        "transfers": 1,
        "distance_km": 265,
        "frequency_per_day": 20,
        "operator": "JR West (Thunderbird + Shinkansen)",
    },
    {
        "from_slug": "osaka",
        "to_slug": "fukuoka",
        "mode": "shinkansen",
        "duration_minutes": 155,
        "transfers": 0,
        "distance_km": 553,
        "frequency_per_day": 40,
        "operator": "JR West (Sanyo Shinkansen)",
    },
    {
        "from_slug": "nagoya",
        "to_slug": "matsumoto",
        "mode": "limited_express",
        "duration_minutes": 125,
        "transfers": 0,
        "distance_km": 188,
        "frequency_per_day": 12,
        "operator": "JR Central (Shinano)",
    },
    {
        "from_slug": "nagoya",
        "to_slug": "takayama",
        "mode": "limited_express",
        "duration_minutes": 145,
        "transfers": 0,
        "distance_km": 166,
        "frequency_per_day": 10,
        "operator": "JR Central (Hida)",
    },
    # ---- Tohoku internal ---------------------------------------------------
    {
        "from_slug": "sendai",
        "to_slug": "matsushima",
        "mode": "local_train",
        "duration_minutes": 40,
        "transfers": 0,
        "distance_km": 25,
        "frequency_per_day": 40,
        "operator": "JR East (Senseki Line)",
    },
    {
        "from_slug": "sendai",
        "to_slug": "yamagata",
        "mode": "highway_bus",
        "duration_minutes": 70,
        "transfers": 0,
        "distance_km": 60,
        "frequency_per_day": 40,
        "operator": "Miyagi Kotsu / Yamako",
        "seasonal_note": "The bus is faster and more frequent than the train on this corridor.",
    },
    {
        "from_slug": "sendai",
        "to_slug": "yamadera",
        "mode": "local_train",
        "duration_minutes": 60,
        "transfers": 0,
        "distance_km": 48,
        "frequency_per_day": 14,
        "operator": "JR East (Senzan Line)",
        "seasonal_note": "Roughly hourly; check the last return before committing to the 1,015 steps.",
    },
    {
        "from_slug": "sendai",
        "to_slug": "zao-onsen",
        "mode": "highway_bus",
        "duration_minutes": 110,
        "transfers": 1,
        "distance_km": 78,
        "last_departure_local": "18:40",
        "final_leg_minutes": 40,
        "frequency_per_day": 12,
        "operator": "Yamako Bus",
    },
    {
        "from_slug": "sendai",
        "to_slug": "ginzan-onsen",
        "mode": "local_train",
        "duration_minutes": 195,
        "transfers": 2,
        "distance_km": 105,
        "last_departure_local": "18:10",
        "final_leg_minutes": 40,
        "frequency_per_day": 8,
        "operator": "JR East + Hanagasa Bus",
        "seasonal_note": "Sendai → Oishida by rail, then the village bus. The last bus into the valley is early and there is no taxi rank at Oishida after dark.",
    },
    {
        "from_slug": "yamagata",
        "to_slug": "ginzan-onsen",
        "mode": "local_train",
        "duration_minutes": 110,
        "transfers": 1,
        "distance_km": 55,
        "last_departure_local": "18:10",
        "final_leg_minutes": 40,
        "frequency_per_day": 8,
        "operator": "JR East (Ou Line) + Hanagasa Bus",
    },
    {
        "from_slug": "ginzan-onsen",
        "to_slug": "aomori",
        "mode": "local_train",
        "duration_minutes": 330,
        "transfers": 3,
        "distance_km": 285,
        "frequency_per_day": 5,
        "operator": "Hanagasa Bus + JR East",
        "seasonal_note": "Bus out of the valley, local line to Shinjo, Shinkansen north. In winter the first bus out is late morning, which effectively costs the whole day.",
    },
    {
        "from_slug": "sendai",
        "to_slug": "aomori",
        "mode": "shinkansen",
        "duration_minutes": 120,
        "transfers": 1,
        "distance_km": 322,
        "frequency_per_day": 15,
        "operator": "JR East (Tohoku Shinkansen)",
    },
    {
        "from_slug": "sendai",
        "to_slug": "morioka",
        "mode": "shinkansen",
        "duration_minutes": 45,
        "transfers": 0,
        "distance_km": 172,
        "frequency_per_day": 30,
        "operator": "JR East",
    },
    {
        "from_slug": "morioka",
        "to_slug": "kakunodate",
        "mode": "shinkansen",
        "duration_minutes": 50,
        "transfers": 0,
        "distance_km": 62,
        "frequency_per_day": 14,
        "operator": "JR East (Akita Shinkansen)",
    },
    {
        "from_slug": "morioka",
        "to_slug": "nyuto-onsen",
        "mode": "local_bus",
        "duration_minutes": 105,
        "transfers": 1,
        "distance_km": 68,
        "last_departure_local": "17:35",
        "final_leg_minutes": 50,
        "frequency_per_day": 7,
        "operator": "JR East + Ugo Kotsu",
        "seasonal_note": "Tazawako Station bus. Some inns run their own pickup but only for confirmed bookings.",
    },
    {
        "from_slug": "aomori",
        "to_slug": "hirosaki",
        "mode": "local_train",
        "duration_minutes": 45,
        "transfers": 0,
        "distance_km": 37,
        "frequency_per_day": 25,
        "operator": "JR East (Ou Line)",
    },
    {
        "from_slug": "aomori",
        "to_slug": "oirase",
        "mode": "local_bus",
        "duration_minutes": 135,
        "transfers": 0,
        "distance_km": 62,
        "last_departure_local": "15:20",
        "final_leg_minutes": 135,
        "frequency_per_day": 4,
        "operator": "JR Bus Tohoku (Mizuumi-go)",
        "seasonal_note": "Green-season only, roughly late April to early November. Four services a day and none after mid-afternoon.",
    },
    {
        "from_slug": "aomori",
        "to_slug": "hakodate",
        "mode": "shinkansen",
        "duration_minutes": 125,
        "transfers": 2,
        "distance_km": 160,
        "frequency_per_day": 10,
        "operator": "JR Hokkaido (Hokkaido Shinkansen)",
        "seasonal_note": "Shin-Aomori to Shin-Hakodate-Hokuto is 1h, but both ends need a local connection into town.",
    },
    {
        "from_slug": "hakodate",
        "to_slug": "tokyo",
        "mode": "shinkansen",
        "duration_minutes": 270,
        "transfers": 1,
        "distance_km": 830,
        "frequency_per_day": 10,
        "operator": "JR Hokkaido/East",
    },
    {
        "from_slug": "aomori",
        "to_slug": "tokyo",
        "mode": "shinkansen",
        "duration_minutes": 200,
        "transfers": 1,
        "distance_km": 675,
        "frequency_per_day": 15,
        "operator": "JR East",
    },
    # ---- Nagano / Alps internal --------------------------------------------
    {
        "from_slug": "nagano",
        "to_slug": "jigokudani",
        "mode": "local_train",
        "duration_minutes": 75,
        "transfers": 1,
        "distance_km": 33,
        "last_departure_local": "16:20",
        "final_leg_minutes": 15,
        "frequency_per_day": 16,
        "operator": "Nagaden + Nagaden Bus",
        "seasonal_note": "The park closes at 16:00 in winter and the walk in takes 35 minutes each way.",
    },
    {
        "from_slug": "nagano",
        "to_slug": "nozawa-onsen",
        "mode": "local_bus",
        "duration_minutes": 100,
        "transfers": 1,
        "distance_km": 55,
        "last_departure_local": "18:30",
        "final_leg_minutes": 25,
        "frequency_per_day": 10,
        "operator": "JR East + Nozawa Onsen Liner",
    },
    {
        "from_slug": "nagano",
        "to_slug": "matsumoto",
        "mode": "limited_express",
        "duration_minutes": 55,
        "transfers": 0,
        "distance_km": 63,
        "frequency_per_day": 18,
        "operator": "JR East (Shinano)",
    },
    {
        "from_slug": "matsumoto",
        "to_slug": "kamikochi",
        "mode": "local_bus",
        "duration_minutes": 95,
        "transfers": 1,
        "distance_km": 45,
        "last_departure_local": "16:50",
        "final_leg_minutes": 65,
        "frequency_per_day": 9,
        "operator": "Alpico Kotsu",
        "seasonal_note": "Closed to all traffic mid-November to mid-April. Private cars are banned year-round; the bus or a taxi are the only ways in.",
    },
    {
        "from_slug": "matsumoto",
        "to_slug": "narai",
        "mode": "local_train",
        "duration_minutes": 60,
        "transfers": 1,
        "distance_km": 42,
        "frequency_per_day": 12,
        "operator": "JR East (Chuo Line)",
        "seasonal_note": "Roughly hourly. Narai has no staffed station and no taxi rank.",
    },
    {
        "from_slug": "matsumoto",
        "to_slug": "takayama",
        "mode": "highway_bus",
        "duration_minutes": 150,
        "transfers": 1,
        "distance_km": 110,
        "last_departure_local": "17:20",
        "final_leg_minutes": 90,
        "frequency_per_day": 5,
        "operator": "Nohi Bus",
        "seasonal_note": "Via Hirayu Onsen. Five services a day; reservations recommended and required in autumn.",
    },
    {
        "from_slug": "takayama",
        "to_slug": "shirakawa-go",
        "mode": "highway_bus",
        "duration_minutes": 55,
        "transfers": 0,
        "distance_km": 50,
        "last_departure_local": "17:40",
        "final_leg_minutes": 55,
        "frequency_per_day": 12,
        "operator": "Nohi Bus",
        "seasonal_note": "Reservation required in peak autumn and during the winter light-up.",
    },
    {
        "from_slug": "shirakawa-go",
        "to_slug": "kanazawa",
        "mode": "highway_bus",
        "duration_minutes": 85,
        "transfers": 0,
        "distance_km": 68,
        "last_departure_local": "17:30",
        "final_leg_minutes": 85,
        "frequency_per_day": 8,
        "operator": "Nohi Bus / Hokutetsu",
    },
    {
        "from_slug": "nagano",
        "to_slug": "hakuba",
        "mode": "highway_bus",
        "duration_minutes": 70,
        "transfers": 0,
        "distance_km": 55,
        "last_departure_local": "19:40",
        "final_leg_minutes": 70,
        "frequency_per_day": 14,
        "operator": "Alpico Kotsu",
    },
    # ---- Hokuriku internal --------------------------------------------------
    {
        "from_slug": "kanazawa",
        "to_slug": "toyama",
        "mode": "shinkansen",
        "duration_minutes": 22,
        "transfers": 0,
        "distance_km": 59,
        "frequency_per_day": 25,
        "operator": "JR West",
    },
    {
        "from_slug": "kanazawa",
        "to_slug": "wajima",
        "mode": "highway_bus",
        "duration_minutes": 125,
        "transfers": 0,
        "distance_km": 110,
        "last_departure_local": "18:00",
        "final_leg_minutes": 125,
        "frequency_per_day": 9,
        "operator": "Hokutetsu Bus",
        "seasonal_note": "The Noto railway closed in 2001. Express bus from Kanazawa Station, or drive.",
    },
    {
        "from_slug": "kanazawa",
        "to_slug": "fukui",
        "mode": "shinkansen",
        "duration_minutes": 40,
        "transfers": 0,
        "distance_km": 76,
        "frequency_per_day": 22,
        "operator": "JR West",
    },
    {
        "from_slug": "fukui",
        "to_slug": "eiheiji",
        "mode": "local_bus",
        "duration_minutes": 35,
        "transfers": 0,
        "distance_km": 17,
        "last_departure_local": "17:05",
        "final_leg_minutes": 35,
        "frequency_per_day": 10,
        "operator": "Keifuku Bus",
    },
    {
        "from_slug": "toyama",
        "to_slug": "tateyama",
        "mode": "local_train",
        "duration_minutes": 60,
        "transfers": 1,
        "distance_km": 30,
        "last_departure_local": "15:00",
        "final_leg_minutes": 25,
        "frequency_per_day": 12,
        "operator": "Toyama Chiho Railway",
        "seasonal_note": "Alpine Route is closed roughly 1 December to mid-April. Last through-traverse departures are early afternoon.",
    },
    # ---- Shikoku / Setouchi internal ----------------------------------------
    {
        "from_slug": "takamatsu",
        "to_slug": "naoshima",
        "mode": "ferry",
        "duration_minutes": 70,
        "transfers": 1,
        "distance_km": 20,
        "last_departure_local": "18:05",
        "final_leg_minutes": 50,
        "frequency_per_day": 5,
        "operator": "Shikoku Kisen",
        "seasonal_note": "Five sailings a day. Missing the last ferry means an unplanned night on the island.",
    },
    {
        "from_slug": "naoshima",
        "to_slug": "teshima",
        "mode": "ferry",
        "duration_minutes": 40,
        "transfers": 0,
        "distance_km": 12,
        "last_departure_local": "16:20",
        "final_leg_minutes": 40,
        "frequency_per_day": 4,
        "operator": "Shikoku Kisen",
        "seasonal_note": "Four sailings and none of them convenient. Both museums close on Tuesdays.",
    },
    {
        "from_slug": "takamatsu",
        "to_slug": "matsuyama",
        "mode": "limited_express",
        "duration_minutes": 155,
        "transfers": 0,
        "distance_km": 194,
        "frequency_per_day": 14,
        "operator": "JR Shikoku (Ishizuchi)",
    },
    {
        "from_slug": "takamatsu",
        "to_slug": "iya-valley",
        "mode": "local_bus",
        "duration_minutes": 200,
        "transfers": 2,
        "distance_km": 95,
        "last_departure_local": "15:45",
        "final_leg_minutes": 60,
        "frequency_per_day": 4,
        "operator": "JR Shikoku + Yonkoh Bus",
        "seasonal_note": "Limited express to Oboke, then the valley bus — four a day, last one mid-afternoon.",
    },
    {
        "from_slug": "iya-valley",
        "to_slug": "kochi",
        "mode": "local_bus",
        "duration_minutes": 165,
        "transfers": 2,
        "distance_km": 85,
        "frequency_per_day": 4,
        "operator": "Yonkoh Bus + JR Shikoku",
    },
    {
        "from_slug": "matsuyama",
        "to_slug": "onomichi",
        "mode": "ferry",
        "duration_minutes": 175,
        "transfers": 2,
        "distance_km": 105,
        "frequency_per_day": 6,
        "operator": "Setouchi Cruising",
        "seasonal_note": "Or 4h by bicycle across the Shimanami Kaido, which is the point of coming.",
    },
    # ---- Kyushu internal ----------------------------------------------------
    {
        "from_slug": "fukuoka",
        "to_slug": "yufuin",
        "mode": "limited_express",
        "duration_minutes": 135,
        "transfers": 0,
        "distance_km": 130,
        "frequency_per_day": 3,
        "operator": "JR Kyushu (Yufuin no Mori)",
        "seasonal_note": "The scenic train runs three times a day and sells out weeks ahead in autumn.",
    },
    {
        "from_slug": "fukuoka",
        "to_slug": "beppu",
        "mode": "limited_express",
        "duration_minutes": 125,
        "transfers": 0,
        "distance_km": 150,
        "frequency_per_day": 15,
        "operator": "JR Kyushu (Sonic)",
    },
    {
        "from_slug": "yufuin",
        "to_slug": "kurokawa-onsen",
        "mode": "highway_bus",
        "duration_minutes": 95,
        "transfers": 0,
        "distance_km": 45,
        "last_departure_local": "16:30",
        "final_leg_minutes": 95,
        "frequency_per_day": 3,
        "operator": "Kyushu Odan Bus",
        "seasonal_note": "Three services a day on the trans-Kyushu route. Reservations required; it fills in autumn.",
    },
    {
        "from_slug": "kurokawa-onsen",
        "to_slug": "aso",
        "mode": "highway_bus",
        "duration_minutes": 60,
        "transfers": 0,
        "distance_km": 32,
        "last_departure_local": "16:40",
        "final_leg_minutes": 60,
        "frequency_per_day": 3,
        "operator": "Kyushu Odan Bus",
    },
    {
        "from_slug": "aso",
        "to_slug": "kumamoto",
        "mode": "local_train",
        "duration_minutes": 80,
        "transfers": 0,
        "distance_km": 50,
        "frequency_per_day": 12,
        "operator": "JR Kyushu (Hohi Line)",
    },
    {
        "from_slug": "fukuoka",
        "to_slug": "kumamoto",
        "mode": "shinkansen",
        "duration_minutes": 45,
        "transfers": 0,
        "distance_km": 118,
        "frequency_per_day": 35,
        "operator": "JR Kyushu",
    },
    {
        "from_slug": "kumamoto",
        "to_slug": "kagoshima",
        "mode": "shinkansen",
        "duration_minutes": 50,
        "transfers": 0,
        "distance_km": 174,
        "frequency_per_day": 30,
        "operator": "JR Kyushu",
    },
    {
        "from_slug": "fukuoka",
        "to_slug": "nagasaki",
        "mode": "limited_express",
        "duration_minutes": 100,
        "transfers": 1,
        "distance_km": 154,
        "frequency_per_day": 20,
        "operator": "JR Kyushu (Relay Kamome + Shinkansen)",
    },
    {
        "from_slug": "kagoshima",
        "to_slug": "yakushima",
        "mode": "ferry",
        "duration_minutes": 180,
        "transfers": 1,
        "distance_km": 135,
        "last_departure_local": "14:30",
        "final_leg_minutes": 120,
        "frequency_per_day": 4,
        "operator": "Tane-Yaku Jetfoil",
        "seasonal_note": "Jetfoil cancels in rough seas; budget a spare day at each end in typhoon season.",
    },
    {
        "from_slug": "kumamoto",
        "to_slug": "takachiho",
        "mode": "highway_bus",
        "duration_minutes": 195,
        "transfers": 1,
        "distance_km": 115,
        "last_departure_local": "15:10",
        "final_leg_minutes": 90,
        "frequency_per_day": 3,
        "operator": "Miyakoh Bus",
        "seasonal_note": "The Takachiho railway closed in 2008. Bus or car only, and the bus is slow.",
    },
    {
        "from_slug": "aso",
        "to_slug": "takachiho",
        "mode": "car",
        "duration_minutes": 75,
        "transfers": 0,
        "distance_km": 48,
        "requires_car": True,
        "operator": "self-drive",
        "seasonal_note": "No usable public-transport equivalent since the Takachiho line closed.",
    },
    {
        "from_slug": "kurokawa-onsen",
        "to_slug": "kumamoto",
        "mode": "car",
        "duration_minutes": 95,
        "transfers": 0,
        "distance_km": 72,
        "requires_car": True,
        "operator": "self-drive",
    },
]
