"""Seed region profiles.

DEMO DATA. Every value here is a plausible, hand-authored approximation used to
demonstrate the system end-to-end without paid credentials. It is marked
``is_demo=True`` at the row level and surfaced as "demo data" in the UI. It is
NOT a verified travel dataset and must not be presented as one.

Five regions only, on purpose: the engineering claim is the pipeline, not
nationwide coverage.
"""

from __future__ import annotations

REGIONS: list[dict] = [
    {
        "code": "tohoku",
        "name": "Tohoku",
        "tagline": "Northern Honshu — onsen towns, mountain shrines, serious food, few foreign visitors.",
        "prefectures": ["Miyagi", "Yamagata", "Aomori", "Akita", "Iwate", "Fukushima"],
        "hub_place_slug": "sendai",
        "lat": 38.60,
        "lon": 140.60,
        "gateways": {
            "Tokyo": {
                "gateway": "Tokyo",
                "hours_one_way": 1.6,
                "primary_mode": "shinkansen",
                "transfers": 0,
                "note": "Tohoku Shinkansen, Tokyo to Sendai, no transfer.",
            },
            "Osaka": {
                "gateway": "Osaka",
                "hours_one_way": 4.6,
                "primary_mode": "shinkansen",
                "transfers": 1,
                "note": "Via Tokyo; a whole travel day each way.",
            },
            "Sapporo": {
                "gateway": "Sapporo",
                "hours_one_way": 4.2,
                "primary_mode": "shinkansen",
                "transfers": 1,
                "note": "Hokkaido Shinkansen via Shin-Hakodate-Hokuto.",
            },
            "Nagoya": {
                "gateway": "Nagoya",
                "hours_one_way": 3.5,
                "primary_mode": "shinkansen",
                "transfers": 1,
            },
        },
        "min_recommended_nights": 3,
        "ideal_nights": 5,
        "max_useful_nights": 10,
        "public_transport_score": 0.68,
        "car_free_possible": True,
        "car_recommended": False,
        "car_required_highlights": ["Oirase Gorge in shoulder season", "inland Akita farmstays"],
        "interest_strength": {
            "food": 0.92,
            "onsen": 0.95,
            "nature": 0.88,
            "culture": 0.80,
            "hiking": 0.78,
            "city": 0.55,
            "coast": 0.70,
            "snow": 0.90,
            "art": 0.45,
            "nightlife": 0.40,
        },
        "seasonal": {
            "month_scores": {
                1: 0.72,
                2: 0.72,
                3: 0.55,
                4: 0.78,
                5: 0.90,
                6: 0.75,
                7: 0.80,
                8: 0.86,
                9: 0.82,
                10: 0.94,
                11: 0.80,
                12: 0.68,
            },
            "notes": {
                1: "Deep snow. Onsen towns are at their best; some mountain roads and trails close.",
                2: "Peak snow season and the big winter festivals; bus timetables thin out.",
                3: "Awkward shoulder: snow melting, greenery not yet arrived.",
                8: "Nebuta, Kanto and Tanabata festivals — accommodation books out months ahead.",
                10: "Best all-round month: autumn colour, clear air, comfortable temperatures.",
            },
        },
        "booking_complexity": 0.55,
        "luggage_friendliness": 0.60,
        "step_free_score": 0.55,
        "typical_daily_cost_jpy": {"budget": 11000, "mid": 21000, "premium": 45000},
        "overlaps_with_visited": ["nikko", "hakone", "kanazawa"],
    },
    {
        "code": "nagano_alps",
        "name": "Nagano & the Japan Alps",
        "tagline": "High mountains within easy reach of Tokyo — alpine valleys, castle towns, snow.",
        "prefectures": ["Nagano", "Gifu (Hida)", "Toyama (Tateyama)"],
        "hub_place_slug": "matsumoto",
        "lat": 36.30,
        "lon": 137.80,
        "gateways": {
            "Tokyo": {
                "gateway": "Tokyo",
                "hours_one_way": 1.5,
                "primary_mode": "shinkansen",
                "transfers": 0,
                "note": "Hokuriku Shinkansen to Nagano; Matsumoto is 2h35 by limited express.",
            },
            "Osaka": {
                "gateway": "Osaka",
                "hours_one_way": 3.3,
                "primary_mode": "limited_express",
                "transfers": 1,
            },
            "Nagoya": {
                "gateway": "Nagoya",
                "hours_one_way": 2.1,
                "primary_mode": "limited_express",
                "transfers": 0,
                "note": "Wide View Shinano to Matsumoto.",
            },
            "Sapporo": {
                "gateway": "Sapporo",
                "hours_one_way": 6.0,
                "primary_mode": "flight",
                "transfers": 2,
            },
        },
        "min_recommended_nights": 2,
        "ideal_nights": 4,
        "max_useful_nights": 8,
        "public_transport_score": 0.72,
        "car_free_possible": True,
        "car_recommended": False,
        "car_required_highlights": ["remote Kiso valley inns", "off-season Hakuba"],
        "interest_strength": {
            "food": 0.72,
            "onsen": 0.85,
            "nature": 0.95,
            "culture": 0.78,
            "hiking": 0.97,
            "city": 0.45,
            "coast": 0.05,
            "snow": 0.95,
            "art": 0.50,
            "nightlife": 0.35,
        },
        "seasonal": {
            "month_scores": {
                1: 0.85,
                2: 0.88,
                3: 0.72,
                4: 0.68,
                5: 0.88,
                6: 0.70,
                7: 0.90,
                8: 0.92,
                9: 0.85,
                10: 0.92,
                11: 0.72,
                12: 0.80,
            },
            "notes": {
                1: "Ski season. Snow monkeys at their most photogenic; alpine hiking is closed.",
                4: "Kamikochi and the Alpine Route are still shut for winter — check opening dates.",
                7: "Alpine hiking season opens; afternoon thunderstorms are routine.",
                10: "Autumn colour moves down the mountain through the month.",
                11: "Kamikochi closes mid-month; many mountain huts shut for the season.",
            },
        },
        "booking_complexity": 0.45,
        "luggage_friendliness": 0.55,
        "step_free_score": 0.45,
        "typical_daily_cost_jpy": {"budget": 12000, "mid": 23000, "premium": 50000},
        "overlaps_with_visited": ["hakone", "nikko", "takayama"],
    },
    {
        "code": "hokuriku",
        "name": "Hokuriku",
        "tagline": "Sea-of-Japan coast — Kanazawa's crafts, Noto's coastline, exceptional seafood.",
        "prefectures": ["Ishikawa", "Toyama", "Fukui"],
        "hub_place_slug": "kanazawa",
        "lat": 36.60,
        "lon": 136.65,
        "gateways": {
            "Tokyo": {
                "gateway": "Tokyo",
                "hours_one_way": 2.6,
                "primary_mode": "shinkansen",
                "transfers": 0,
                "note": "Hokuriku Shinkansen Kagayaki, Tokyo to Kanazawa direct.",
            },
            "Osaka": {
                "gateway": "Osaka",
                "hours_one_way": 2.6,
                "primary_mode": "limited_express",
                "transfers": 1,
                "note": "Thunderbird to Tsuruga, then Hokuriku Shinkansen.",
            },
            "Nagoya": {
                "gateway": "Nagoya",
                "hours_one_way": 2.5,
                "primary_mode": "limited_express",
                "transfers": 1,
            },
            "Sapporo": {
                "gateway": "Sapporo",
                "hours_one_way": 5.5,
                "primary_mode": "flight",
                "transfers": 2,
            },
        },
        "min_recommended_nights": 2,
        "ideal_nights": 4,
        "max_useful_nights": 7,
        "public_transport_score": 0.74,
        "car_free_possible": True,
        "car_recommended": False,
        "car_required_highlights": ["outer Noto Peninsula", "Fukui coastal villages"],
        "interest_strength": {
            "food": 0.95,
            "onsen": 0.75,
            "nature": 0.72,
            "culture": 0.90,
            "hiking": 0.55,
            "city": 0.70,
            "coast": 0.88,
            "snow": 0.70,
            "art": 0.82,
            "nightlife": 0.45,
        },
        "seasonal": {
            "month_scores": {
                1: 0.72,
                2: 0.70,
                3: 0.68,
                4: 0.85,
                5: 0.90,
                6: 0.72,
                7: 0.78,
                8: 0.78,
                9: 0.80,
                10: 0.90,
                11: 0.88,
                12: 0.78,
            },
            "notes": {
                1: "Winter seafood — snow crab season. Grey, wet and genuinely atmospheric.",
                11: "Snow crab season opens; Kenrokuen's yukitsuri ropes go up.",
                4: "Tateyama Alpine Route reopens with the snow corridor at its highest.",
            },
        },
        "booking_complexity": 0.40,
        "luggage_friendliness": 0.78,
        "step_free_score": 0.72,
        "typical_daily_cost_jpy": {"budget": 11000, "mid": 22000, "premium": 48000},
        "overlaps_with_visited": ["kyoto", "kanazawa", "takayama"],
    },
    {
        "code": "shikoku_setouchi",
        "name": "Shikoku & the Seto Inland Sea",
        "tagline": "Island-hopping art, the oldest onsen in Japan, and a gorge valley almost nobody reaches.",
        "prefectures": ["Kagawa", "Ehime", "Tokushima", "Kochi", "Okayama (Setouchi)"],
        "hub_place_slug": "takamatsu",
        "lat": 34.10,
        "lon": 133.70,
        "gateways": {
            "Osaka": {
                "gateway": "Osaka",
                "hours_one_way": 2.0,
                "primary_mode": "limited_express",
                "transfers": 1,
                "note": "Shinkansen to Okayama, then Marine Liner to Takamatsu.",
            },
            "Tokyo": {
                "gateway": "Tokyo",
                "hours_one_way": 4.4,
                "primary_mode": "shinkansen",
                "transfers": 1,
                "note": "Tokyo to Okayama, then across the Seto-Ohashi bridge.",
            },
            "Fukuoka": {
                "gateway": "Fukuoka",
                "hours_one_way": 3.4,
                "primary_mode": "shinkansen",
                "transfers": 1,
            },
            "Nagoya": {
                "gateway": "Nagoya",
                "hours_one_way": 3.2,
                "primary_mode": "shinkansen",
                "transfers": 1,
            },
        },
        "min_recommended_nights": 3,
        "ideal_nights": 5,
        "max_useful_nights": 9,
        "public_transport_score": 0.52,
        "car_free_possible": True,
        "car_recommended": True,
        "car_required_highlights": ["Iya Valley beyond Oboke", "inland Kochi", "Cape Ashizuri"],
        "interest_strength": {
            "food": 0.82,
            "onsen": 0.85,
            "nature": 0.80,
            "culture": 0.78,
            "hiking": 0.62,
            "city": 0.40,
            "coast": 0.95,
            "snow": 0.10,
            "art": 0.96,
            "nightlife": 0.30,
        },
        "seasonal": {
            "month_scores": {
                1: 0.60,
                2: 0.62,
                3: 0.78,
                4: 0.90,
                5: 0.92,
                6: 0.65,
                7: 0.78,
                8: 0.72,
                9: 0.82,
                10: 0.92,
                11: 0.90,
                12: 0.65,
            },
            "notes": {
                4: "Ideal island weather; Setouchi Triennale years get very busy in spring.",
                6: "Rainy season; ferries still run but island days lose their point in heavy rain.",
                8: "Hot and humid, and the islands offer little shade.",
                11: "Best month: settled weather, clear sea light, comfortable cycling on Shimanami.",
            },
        },
        "booking_complexity": 0.62,
        "luggage_friendliness": 0.48,
        "step_free_score": 0.50,
        "typical_daily_cost_jpy": {"budget": 10000, "mid": 20000, "premium": 42000},
        "overlaps_with_visited": ["osaka", "hiroshima", "kyoto"],
    },
    {
        "code": "kyushu",
        "name": "Kyushu",
        "tagline": "Volcanoes, the country's best onsen density, and a food culture of its own.",
        "prefectures": ["Fukuoka", "Oita", "Kumamoto", "Kagoshima", "Nagasaki", "Miyazaki"],
        "hub_place_slug": "fukuoka",
        "lat": 32.80,
        "lon": 130.80,
        "gateways": {
            "Fukuoka": {
                "gateway": "Fukuoka",
                "hours_one_way": 0.3,
                "primary_mode": "local_train",
                "transfers": 0,
                "note": "Fukuoka Airport is two subway stops from Hakata — the fastest airport transfer in Japan.",
            },
            "Osaka": {
                "gateway": "Osaka",
                "hours_one_way": 2.6,
                "primary_mode": "shinkansen",
                "transfers": 0,
            },
            "Tokyo": {
                "gateway": "Tokyo",
                "hours_one_way": 5.1,
                "primary_mode": "shinkansen",
                "transfers": 0,
                "note": "Direct Nozomi exists but is a full travel day; flying is 2h door to gate.",
            },
            "Sapporo": {
                "gateway": "Sapporo",
                "hours_one_way": 4.5,
                "primary_mode": "flight",
                "transfers": 1,
            },
        },
        "min_recommended_nights": 4,
        "ideal_nights": 6,
        "max_useful_nights": 12,
        "public_transport_score": 0.62,
        "car_free_possible": True,
        "car_recommended": True,
        "car_required_highlights": [
            "Aso caldera rim",
            "Kurokawa Onsen",
            "Takachiho Gorge",
            "inland Miyazaki",
        ],
        "interest_strength": {
            "food": 0.94,
            "onsen": 0.97,
            "nature": 0.88,
            "culture": 0.75,
            "hiking": 0.72,
            "city": 0.72,
            "coast": 0.80,
            "snow": 0.15,
            "art": 0.45,
            "nightlife": 0.78,
        },
        "seasonal": {
            "month_scores": {
                1: 0.72,
                2: 0.72,
                3: 0.85,
                4: 0.90,
                5: 0.88,
                6: 0.55,
                7: 0.62,
                8: 0.60,
                9: 0.70,
                10: 0.90,
                11: 0.92,
                12: 0.75,
            },
            "notes": {
                6: "Rainy season is genuinely heavy here, and landslides close mountain roads.",
                8: "Typhoon season; ferry and flight disruption is common.",
                11: "Best month: autumn colour in Aso and Kirishima, comfortable onsen weather.",
            },
        },
        "booking_complexity": 0.50,
        "luggage_friendliness": 0.70,
        "step_free_score": 0.65,
        "typical_daily_cost_jpy": {"budget": 10000, "mid": 20000, "premium": 46000},
        "overlaps_with_visited": ["osaka", "hiroshima"],
    },
]
