"""MCP server definition.

Tools are declared with **flat** parameters rather than a single wrapper object,
because that is what produces a clean top-level JSON Schema for consumers — an
LLM planning a call sees ``from_place`` / ``to_place``, not
``args: {$ref: SearchTransportInput}``. Each handler immediately reconstructs the
shared Pydantic contract from ``shared_schemas``, so field constraints
(lengths, ranges, enum membership) are still enforced in exactly one place and a
malformed call is rejected before the backend is touched.

The instructions string is served to MCP clients and states the safety boundary:
this gateway cannot book, pay, or contact anyone.
"""

from __future__ import annotations

from mcp.server.mcpserver import MCPServer

from shared_schemas.tools import (
    TOOL_CONTRACTS,
    CalculateTravelLoadInput,
    CalculateTravelLoadOutput,
    CheckRouteConstraintsInput,
    CheckRouteConstraintsOutput,
    CreateHumanReviewInput,
    CreateHumanReviewOutput,
    GetBookingRequirementsInput,
    GetBookingRequirementsOutput,
    GetPlaceConstraintsInput,
    GetPlaceConstraintsOutput,
    GetPlaceDetailsInput,
    GetPlaceDetailsOutput,
    GetRouteContextInput,
    GetRouteContextOutput,
    GetSourceEvidenceInput,
    GetSourceEvidenceOutput,
    GetTripContextInput,
    GetTripContextOutput,
    GetVerificationStatusInput,
    GetVerificationStatusOutput,
    GetWeatherContextInput,
    GetWeatherContextOutput,
    SaveTripDecisionInput,
    SaveTripDecisionOutput,
    SearchEvidenceInput,
    SearchEvidenceOutput,
    SearchTransportInput,
    SearchTransportOutput,
)
from travel_mcp.backend import TravelBackend

SERVER_NAME = "travel-intelligence-mcp"
SERVER_VERSION = "0.1.0"

INSTRUCTIONS = """\
Verified regional-Japan travel intelligence.

Use these tools instead of recalling travel facts. Transport durations, booking
rules, closure windows and last-departure times come from verified records or
clearly-labelled estimates; nothing here is generated by a language model.

Results carry provenance: evidence ids, source ids, verification dates, a
freshness state, and an `is_demo` flag. Cite them. When a fact is missing or
stale, say so and call create_human_review_request rather than guessing.

This gateway is read-mostly. `save_trip_decision` writes trip memory and nothing
else. No tool here can book, pay for, or cancel anything, or contact any person
or business.
"""


def build_server(backend: TravelBackend, *, name: str = SERVER_NAME) -> MCPServer:
    server = MCPServer(name=name, version=SERVER_VERSION, instructions=INSTRUCTIONS)

    def _desc(tool: str) -> str:
        return TOOL_CONTRACTS[tool].description

    # ---- evidence ---------------------------------------------------------
    @server.tool(name="search_verified_evidence", description=_desc("search_verified_evidence"))
    async def search_verified_evidence(
        query: str,
        region_codes: list[str] | None = None,
        place_slugs: list[str] | None = None,
        topics: list[str] | None = None,
        month: int | None = None,
        official_only: bool = False,
        limit: int = 6,
    ) -> SearchEvidenceOutput:
        return await backend.search_verified_evidence(
            SearchEvidenceInput(
                query=query,
                region_codes=region_codes or [],
                place_slugs=place_slugs or [],
                topics=topics or [],
                month=month,
                official_only=official_only,
                limit=limit,
            )
        )

    @server.tool(name="get_source_evidence", description=_desc("get_source_evidence"))
    async def get_source_evidence(
        evidence_ids: list[str] | None = None, source_id: str | None = None
    ) -> GetSourceEvidenceOutput:
        return await backend.get_source_evidence(
            GetSourceEvidenceInput(evidence_ids=evidence_ids or [], source_id=source_id)
        )

    # ---- places -----------------------------------------------------------
    @server.tool(name="get_place_details", description=_desc("get_place_details"))
    async def get_place_details(query: str) -> GetPlaceDetailsOutput:
        return await backend.get_place_details(GetPlaceDetailsInput(query=query))

    @server.tool(name="get_place_constraints", description=_desc("get_place_constraints"))
    async def get_place_constraints(
        place_slug: str, month: int | None = None
    ) -> GetPlaceConstraintsOutput:
        return await backend.get_place_constraints(
            GetPlaceConstraintsInput(place_slug=place_slug, month=month)
        )

    # ---- transport --------------------------------------------------------
    @server.tool(name="search_transport", description=_desc("search_transport"))
    async def search_transport(
        from_place: str,
        to_place: str,
        travel_date: str | None = None,
        allow_car: bool = True,
    ) -> SearchTransportOutput:
        return await backend.search_transport(
            SearchTransportInput(
                from_place=from_place,
                to_place=to_place,
                travel_date=travel_date,
                allow_car=allow_car,
            )
        )

    @server.tool(name="get_route_context", description=_desc("get_route_context"))
    async def get_route_context(
        place_slugs: list[str],
        nights: list[int] | None = None,
        allow_car: bool = True,
        arrival_city: str | None = None,
        departure_city: str | None = None,
    ) -> GetRouteContextOutput:
        return await backend.get_route_context(
            GetRouteContextInput(
                place_slugs=place_slugs,
                nights=nights or [],
                allow_car=allow_car,
                arrival_city=arrival_city,
                departure_city=departure_city,
            )
        )

    @server.tool(name="calculate_travel_load", description=_desc("calculate_travel_load"))
    async def calculate_travel_load(
        place_slugs: list[str], nights: list[int], allow_car: bool = True
    ) -> CalculateTravelLoadOutput:
        return await backend.calculate_travel_load(
            CalculateTravelLoadInput(place_slugs=place_slugs, nights=nights, allow_car=allow_car)
        )

    @server.tool(name="check_route_constraints", description=_desc("check_route_constraints"))
    async def check_route_constraints(
        place_slugs: list[str],
        nights: list[int],
        public_transport_only: bool = False,
        large_luggage: bool = False,
        pace: str | None = None,
        arrival_city: str | None = None,
        departure_city: str | None = None,
        month: int | None = None,
    ) -> CheckRouteConstraintsOutput:
        return await backend.check_route_constraints(
            CheckRouteConstraintsInput(
                place_slugs=place_slugs,
                nights=nights,
                public_transport_only=public_transport_only,
                large_luggage=large_luggage,
                pace=pace,
                arrival_city=arrival_city,
                departure_city=departure_city,
                month=month,
            )
        )

    # ---- booking / weather ------------------------------------------------
    @server.tool(name="get_booking_requirements", description=_desc("get_booking_requirements"))
    async def get_booking_requirements(
        place_slugs: list[str], month: int | None = None
    ) -> GetBookingRequirementsOutput:
        return await backend.get_booking_requirements(
            GetBookingRequirementsInput(place_slugs=place_slugs, month=month)
        )

    @server.tool(name="get_weather_context", description=_desc("get_weather_context"))
    async def get_weather_context(place_slug: str, month: int) -> GetWeatherContextOutput:
        return await backend.get_weather_context(
            GetWeatherContextInput(place_slug=place_slug, month=month)
        )

    # ---- verification / HITL ----------------------------------------------
    @server.tool(name="get_verification_status", description=_desc("get_verification_status"))
    async def get_verification_status(
        subjects: list[str] | None = None,
        region_code: str | None = None,
        stale_only: bool = False,
        limit: int = 25,
    ) -> GetVerificationStatusOutput:
        return await backend.get_verification_status(
            GetVerificationStatusInput(
                subjects=subjects or [],
                region_code=region_code,
                stale_only=stale_only,
                limit=limit,
            )
        )

    @server.tool(
        name="create_human_review_request",
        description=_desc("create_human_review_request"),
    )
    async def create_human_review_request(
        reason: str,
        subject: str,
        question: str,
        field_name: str | None = None,
        candidate_values: list[str] | None = None,
        evidence_ids: list[str] | None = None,
        analysis_id: str | None = None,
        thread_id: str | None = None,
        priority: str = "normal",
    ) -> CreateHumanReviewOutput:
        return await backend.create_human_review_request(
            CreateHumanReviewInput(
                reason=reason,
                subject=subject,
                question=question,
                field_name=field_name,
                candidate_values=candidate_values or [],
                evidence_ids=evidence_ids or [],
                analysis_id=analysis_id,
                thread_id=thread_id,
                priority=priority,
            )
        )

    # ---- trip state -------------------------------------------------------
    @server.tool(name="get_trip_context", description=_desc("get_trip_context"))
    async def get_trip_context(trip_id: str) -> GetTripContextOutput:
        return await backend.get_trip_context(GetTripContextInput(trip_id=trip_id))

    @server.tool(name="save_trip_decision", description=_desc("save_trip_decision"))
    async def save_trip_decision(
        trip_id: str,
        decision_kind: str,
        region_code: str | None = None,
        reason: str | None = None,
        preference_key: str | None = None,
        preference_value: str | None = None,
        note: str | None = None,
    ) -> SaveTripDecisionOutput:
        return await backend.save_trip_decision(
            SaveTripDecisionInput(
                trip_id=trip_id,
                decision_kind=decision_kind,
                region_code=region_code,
                reason=reason,
                preference_key=preference_key,
                preference_value=preference_value,
                note=note,
            )
        )

    return server


def tool_names() -> list[str]:
    return sorted(TOOL_CONTRACTS)
